apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-query
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-query
  template:
    metadata:
      labels:
        app: backend-query
    spec:
      containers:
      - name: backend-query
        image: backend-query:1.0.0
        ports:
        - containerPort: 8000
